service: fibonacci

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  calcFibonacci:
    handler: app/controllers/calc-term-fibonacci.calcTermFibonacci
    events:
      - http:
          path: /
          method: get
          private: true
  
  printSequenceFibonacci:
    handler: app/controllers/calc-term-fibonacci.printSequenceFibonacci
    events:
      - http:
          path: /sequence
          method: get
          private: true

